### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by allo-** [pimoroni/enviro-phat#10]
The `envirophat` module is missing a dependency on `smbus`.

**Comment by Gadgetoid** [comment]
Unfortunately this is the less frustrating of two compromises- the "python-smbus" package from apt is required to satisfy a dependency on smbus on a Pi. This package does not exist on the python package index. Adding smbus as a dependency would just break the package in cases where it's not already installed.

**Comment by allo-** [comment]
I saw this when installing it. The problem is, if your create a default `virtualenv` you cannot access the system smbus as well. So you need `--system-site-packages`. I am not sure if somewhere should be a hint for it, or if it's too confusing for new programmers.

Another issue i ran into: you need to enable I2C first. No problem via `config.txt` or `raspi-config`, but there is no obvious hint, that the board uses I2C.

**Comment by Gadgetoid** [comment]
I'll add "Full detailed install instructions" to our ongoing practises, so advanced users (who wont necessarily use the one-line installer) can get some understanding of what's required.
