### ISSUE TITLE
Installation command rejected?

### ISSUE THREAD

**Issue by WongTszLai** [pimoroni/enviro-phat#15]
I did the following command for the installation on a new Pi 3 (after a apt-get update).

curl -sS https://get.pimoroni.com/envirophat | bash

The instructions appeared, saying that it needs I2C communication, and asks if I wish to continue. I type a 'y', and the following error appears:

Checking environment...
We can't connect to the internet, check your network!

I did a few checks, my nameserver is fine, i can ping www.google.com, I can open shop.pimoroni.com on the web browser. I don't think there is any firewall on pi 3.

Am I missing something on the installation?

Is there any alternate installation methods, or can you guide the prerequisites to get it to work?

**Comment by RogueM** [comment]
it's a bug in the installer, I'm going to try to push the fix live since we _think_ we have identified the problem!

**Comment by RogueM** [comment]
if you wish to 'fast track' your installation though, i.e not have to wait for the revised script to be pushed live, you can use the following command:

`curl -sS https://raw.githubusercontent.com/pimoroni/get/master/installers/envirophat | bash
`

**Comment by WongTszLai** [comment]
[enviro error.txt](https://github.com/pimoroni/enviro-phat/files/556091/enviro.error.txt)
Had some error while using the command you provided. Does it have certain requirements before installation?

**Comment by RogueM** [comment]
well it is trying to compile RPi.GPIO from the pypi source... that should not happen. It probably means that your system is not fully up-to-date. In fact I can see it: `RPi.GPIO 0.6.1` (the latest version is 0.6.2)

try: `sudo apt-get upgrade` then the script again.... it may take a while as by the looks of it it has been anywhere between 8-10 months you haven't updated your system ;-)

**Comment by WongTszLai** [comment]
Hi RogueM,

Managed to upgrade and test the functions. Seems everything is fine.

Would like to ask if all the pins on the pi are used? Or are there spare ones that we still can tap on?

Lastly, do you think it might be a good idea to include the command you provided in the readme until you can fix the script? Would also be good if you can provide what we need to update, instead of apt-get upgrade since it takes ages and might have a lot of redundant features being upgraded.

Thanks

**Comment by RogueM** [comment]
It is important you keep your system up-to-date. If there are software on your pi you do not need I advise you remove it.

Check http://pinout.xyz for detailed pinout.
