### ISSUE TITLE
'Sudo python' for use

### ISSUE THREAD

**Issue by bsimmo** [pimoroni/enviro-phat#20]
Why are we needing to run python as sudo for use as per the instructions.
Nothing else I use needs to run as sudo, none of the various i2c devices/sensors I have need it.
What's the issues here ?
(So I know what not to use).

**Comment by Gadgetoid** [comment]
Which instructions?

**Comment by bsimmo** [comment]
Guides and tutorials link, then Getting started (so 'Getting started with the Environment pHAT on Pimoroni)
Specifically states use 'sudo python' to open up a new python prompt for use.
At a recent PiJam that was then the used method. Which seems bad practice to me?

**Comment by RogueM** [comment]
yes, I agree wholeheartedly it is bad practise. However, a lot of our guides were written at a time `rpi.gpio` required elevated privileges, so it is not unusual to come across instructions that feature commands enforcing sudo on many sites dealing with physical computing on the Pi.

In fact, looking outside our learn portal, I have found most people don't even put much thoughts into it even when writing instructions from scratch in 2017, and blindly precede everything with `sudo`. Again, I can only concur it would be best avoided, and in many cases can be.

... anyhow we'll try to fix our older guides in the learn portal, but I wanted to outline the context they were written in (when it wasn't wise to assume users were running a recent version of `rpi.gpio`).

Ultimately, regardless of whatever guide you find that tells you to 'run a command with sudo', I think it is a good exercise to run it without and learn from the outcome i.e did the command succeed or complain? and try to figure out why in the later case (and by that I mean why is elevated privilege required), you'll learn something from it :)

**Comment by bsimmo** [comment]
I will, just waiting for it to be delivered :-).
This is for my son after using it at Pi Jam (we were connecting it to the Hull LoRA network internet of things).
He enjoyed using it, I only asked as it was released a while after sudo was no longer needed for GPIO. So wondered if something on it did need it.
My only shame is you use GPIO4 the 1-wire default pin for the led.  It just makes it a bit more faffy to use 1-wire at the same time,but it impossible.

**Comment by RogueM** [comment]
I don't recall when enviro-phat came out, but it certainly would have been only a small time after jessie was released, and AFAIK there was never a Wheezy release of RPi.GPIO with 'sudo-less' capabilities.

Still, while we can't really assume that all users will have migrated even a year plus on from the pHAT release, I think it's a reasonable comment and it is on our todo list to go through all our tutorials and try to be more discerning in this respect.

**Comment by Gadgetoid** [comment]
I'll have to admit that clashing the LED pin with 1-wire was a silly, avoidable blunder on my part! Although I think that choice pre-dated my running some analytics on our database (pinout.xyz) of Raspberry Pi add-ons and finding GPIO pins which were seldom used, and was probably motivated for ease of routing!

**Comment by Gadgetoid** [comment]
I couldn't find any reference to `sudo` in this guide: https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-enviro-phat - so I think we've since updated it. If you find any other mentions, I'll be keen to know. For now, though, I'm considering this issue resolved and closing it!
