### ISSUE TITLE
Importing from envirophat fails on zero

### ISSUE THREAD

**Issue by ssciarrino** [pimoroni/enviro-phat#21]
This is the error I'm getting it is a brand new install on a raspberry zero.
Thanks
Scott

Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from envirophat import weather
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/envirophat/__init__.py", line 12, in <module>
    light = tcs3472(bus)
  File "/usr/lib/python3/dist-packages/envirophat/tcs3472.py", line 37, in __init__
    self.i2c_bus.write_byte_data(ADDR, REG_ENABLE, REG_ENABLE_RGBC | REG_ENABLE_POWER)
OSError: [Errno 5] Input/output error
>>> from envirophat import light
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/envirophat/__init__.py", line 12, in <module>
    light = tcs3472(bus)
  File "/usr/lib/python3/dist-packages/envirophat/tcs3472.py", line 37, in __init__
    self.i2c_bus.write_byte_data(ADDR, REG_ENABLE, REG_ENABLE_RGBC | REG_ENABLE_POWER)
OSError: [Errno 5] Input/output error
>>> exit()

**Comment by ssciarrino** [comment]
pi@raspberrypi:~ $ python3 -c "import smbus;bus = smbus.SMBus(1);print(dir(bus))"
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'block_process_call', 'close', 'open', 'pec', 'process_call', 'read_block_data', 'read_byte', 'read_byte_data', 'read_i2c_block_data', 'read_word_data', 'write_block_data', 'write_byte', 'write_byte_data', 'write_i2c_block_data', 'write_quick', 'write_word_data']

**Comment by Gadgetoid** [comment]
Could you post details of your wiring/soldering? The IOError is happening in the first command sent to the first i2c device on Enviro pHAT which suggests there's a flaky connection to the pHAT. You'd see this same error if you ran the code with no Enviro pHAT connected at all.
