### ISSUE TITLE
Loading script on boot: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by k0walik** [pimoroni/enviro-phat#22]
I am trying to run my custom script as background daemon which is being loaded during startup via rc.local script. During execution any access to envirophat throws:

> OSError: [Errno 25] Inappropriate ioctl for device

However, same script loaded as background daemon from command line does not raise mentioned exception. I have tried to run it as root and as regular user, but there is no difference. The only workaround I found is to defer loading library to function scope. 

Please refer to [script](https://github.com/KowalikPL/RPiZeroScripts/blob/master/data_uploader/src/data_uploader.py#L52) file for error reproduction. I am using RPi Zero W with latest Raspbian image, no other shields are connected.

**Comment by Gadgetoid** [comment]
Could this be related? https://forums.pimoroni.com/t/enviro-phat-and-daemonizing/6224
