### ISSUE TITLE
Error when passing unit kwarg into pressure(self, unit=None)

### ISSUE THREAD

**Issue by nickever** [pimoroni/enviro-phat#29]
When attempting to pass the kwarg 'unit' into the pressure function:
`envirophat.weather.pressure(unit='hPa')`

 I got the following error:
`TypeError: pressure() got an unexpected keyword argument 'unit'`

Is this the expected behaviour or should the function handle the unit keyword?

**Comment by Gadgetoid** [comment]
This change is currently unreleased, you need to install the library from GitHub to use it.

```
git clone https://github.com/pimoroni/enviro-phat
cd enviro-phat/library
sudo python setup.py install
```

**Comment by nickever** [comment]
Thanks @Gadgetoid - my installed version (v0.0.6) matches the __init.py__ version, so I was under the impression I was working with the same version as appears in this repo. Thanks for the correction.
