### ISSUE TITLE
Enviro phat not conecting.

### ISSUE THREAD

**Issue by CoffeeList1278** [pimoroni/enviro-phat#32]
Hi, 
my enviro phat is not able to be seen on my RaspberryPi. I can't do anything with it, since I don't even see it on I2C bus.

What should I do about it?

**Comment by bsimmo** [comment]
Have you followed the instructions and enabled the I2C bus in Raspi-config or the desktop version of configuration settings

**Comment by CoffeeList1278** [comment]
Yes, 
I have enabled the I2C bus in configuration. I have also installed all drivers with dependencies.

**Comment by bsimmo** [comment]
I doubt it is a problem with the Python modules. Go to the Pimoroni Forums
and ask there, or email them for support.
