### ISSUE TITLE
Missing unit argument in learn guide

### ISSUE THREAD

**Issue by aerialist** [pimoroni/enviro-phat#33]
Thanks for the great product with nice code!

I just noticed an issue on the learning guide. Sorry if this is not the right place to report.

https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-enviro-phat

> And to read the pressure in hPa (hecto Pascals), type the following:
> 
> `print(weather.pressure())`

The code to report in hPa should specify unit argument

`print(weather.pressure(unit='hPa')`

**Comment by sandyjmacdonald** [comment]
Thanks for spotting that! I've updated the tutorial accordingly. :-)
