### ISSUE TITLE
Remote I/O Error

### ISSUE THREAD

**Issue by C-D-Lewis** [pimoroni/enviro-phat#40]
Hi, I just took delivery of a shiny new (white!) enviro phat, and am having problems getting it to work.

I'm using a Pi Zero W:

```
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 00000000e4780010
Model		: Raspberry Pi Zero W Rev 1.1
```

with `apt-get update` and `apt-get upgrade` all up to date, and I can see i2c devices attached when the phat is in place:

```
pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- 23 -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --
```

Yet, when I try and follow the tutorial, or run any of the `examples`, I get the same error:

```
pi@raspberrypi:~ $ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from envirophat import light
>>> light.light()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/envirophat/tcs3472.py", line 80, in light
    return self.raw()[CH_CLEAR]
  File "/usr/lib/python2.7/dist-packages/envirophat/tcs3472.py", line 88, in raw
    self.setup()
  File "/usr/lib/python2.7/dist-packages/envirophat/tcs3472.py", line 44, in setup
    self.i2c_bus.write_byte_data(ADDR, REG_ENABLE, REG_ENABLE_RGBC | REG_ENABLE_POWER)
IOError: [Errno 121] Remote I/O error
```

Am I missing anything or doing anything wrong? I'd love to get started with this module! 

Is this repo still viable for the newer white version of this board?

**Comment by Gadgetoid** [comment]
Took me a second to realise what was happening, but I think you want this library over here -> https://github.com/pimoroni/enviroplus-python/

**Comment by C-D-Lewis** [comment]
@Gadgetoid Thanks for the speedy response. 

As far as I know, I don't have the 'plus' version (https://shop.pimoroni.com/products/enviro?variant=31155658489939), but if this other library is still appropriate I will give it a spin!

**Comment by Gadgetoid** [comment]
Indeed, the other library still applies! I should probably add a notice onto this library to clarify that- since it's definitely not clear right now.

**Comment by C-D-Lewis** [comment]
![](https://media.giphy.com/media/9K2nFglCAQClO/200.gif)

Please feel free to close. A note in this repo's README pointing me in the right direction if I have the newer white board (whether or not it's a + edition) would be very useful, and I would have gone straight there :)

**Comment by Gadgetoid** [comment]
Have updated the README- hopefully sufficient! Thanks for forging the way for future lost customers.

**Comment by C-D-Lewis** [comment]
I used to write docs for a living - this is how these things get fixed. Thanks for the quick docs update :muscle:
