### ISSUE TITLE
light sensor: division by zero

### ISSUE THREAD

**Issue by rezgalis** [pimoroni/enviro-phat#8]
Hi,
I left the pHat on for solid 24hours and spotted that during night time (presumably light=0, probably the same with rgb values) the readings would fail because of the bit in tcs3472.py lib:

``` sh
 File "/usr/local/lib/python2.7/dist-packages/envirophat/tcs3472.py", line 51, in rgb
    return tuple([int(x * 255) for x in self.scaled()][:3])
  File "/usr/local/lib/python2.7/dist-packages/envirophat/tcs3472.py", line 48, in scaled
    return tuple([float(x) / rgbc[3] for x in rgbc])
ZeroDivisionError: float division by zero
```

I know I could wrap my code with try-except, but probably it might be worth introducing a bit of logic in the function scaled() to e.g. simply return 0 or split by 1 if rgbc[3]==0 ? (sorry, a bit of rookie here, don't take my idea for granted :) ).

**Comment by Gadgetoid** [comment]
This was already fixed in https://github.com/pimoroni/enviro-phat/commit/03c2a58adf96ce5c2dc578e534a31d3e4b851c52, however it's not yet made it to a deployed package release. I'll rectify that ASAP.
